version: '3.2'
services:
  mysql:
    image: mysql
    container_name: source-db
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 3306:3306
    volumes:
      - ./etc/mysql:/etc/mysql/conf.d

  metrics-gateway:
    image: prom/pushgateway
    ports:
      - 9091:9091

  node-exporter:
      image: prom/node-exporter
      ports:
       - "9100:9100"

  prometheus-server:
    image: prom/prometheus
    ports:
      - 9090:9090
    links:
      - metrics-gateway:metrics-gateway
    volumes:
      - ./etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana-ui:
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret
    links:
      - prometheus-server:prometheus