version: '3.2'
services:
  mysql:
    image: mysql
    container_name: source-db
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 3306:3306
    volumes:
      - ./resources/etc:/etc/mysql/conf.d